# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zaydm/bin/g/z-ed

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zaydm/bin/g/z-ed

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zaydm/bin/g/z-ed/CMakeFiles /home/zaydm/bin/g/z-ed//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zaydm/bin/g/z-ed/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named comm

# Build rule for target.
comm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 comm
.PHONY : comm

# fast build rule for target.
comm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/comm.dir/build.make CMakeFiles/comm.dir/build
.PHONY : comm/fast

#=============================================================================
# Target rules for targets named commproc

# Build rule for target.
commproc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 commproc
.PHONY : commproc

# fast build rule for target.
commproc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/commproc.dir/build.make CMakeFiles/commproc.dir/build
.PHONY : commproc/fast

src/comm.o: src/comm.c.o
.PHONY : src/comm.o

# target to build an object file
src/comm.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/comm.dir/build.make CMakeFiles/comm.dir/src/comm.c.o
.PHONY : src/comm.c.o

src/comm.i: src/comm.c.i
.PHONY : src/comm.i

# target to preprocess a source file
src/comm.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/comm.dir/build.make CMakeFiles/comm.dir/src/comm.c.i
.PHONY : src/comm.c.i

src/comm.s: src/comm.c.s
.PHONY : src/comm.s

# target to generate assembly for a file
src/comm.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/comm.dir/build.make CMakeFiles/comm.dir/src/comm.c.s
.PHONY : src/comm.c.s

src/commproc.o: src/commproc.c.o
.PHONY : src/commproc.o

# target to build an object file
src/commproc.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/commproc.dir/build.make CMakeFiles/commproc.dir/src/commproc.c.o
.PHONY : src/commproc.c.o

src/commproc.i: src/commproc.c.i
.PHONY : src/commproc.i

# target to preprocess a source file
src/commproc.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/commproc.dir/build.make CMakeFiles/commproc.dir/src/commproc.c.i
.PHONY : src/commproc.c.i

src/commproc.s: src/commproc.c.s
.PHONY : src/commproc.s

# target to generate assembly for a file
src/commproc.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/commproc.dir/build.make CMakeFiles/commproc.dir/src/commproc.c.s
.PHONY : src/commproc.c.s

src/lib.o: src/lib.c.o
.PHONY : src/lib.o

# target to build an object file
src/lib.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/commproc.dir/build.make CMakeFiles/commproc.dir/src/lib.c.o
.PHONY : src/lib.c.o

src/lib.i: src/lib.c.i
.PHONY : src/lib.i

# target to preprocess a source file
src/lib.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/commproc.dir/build.make CMakeFiles/commproc.dir/src/lib.c.i
.PHONY : src/lib.c.i

src/lib.s: src/lib.c.s
.PHONY : src/lib.s

# target to generate assembly for a file
src/lib.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/commproc.dir/build.make CMakeFiles/commproc.dir/src/lib.c.s
.PHONY : src/lib.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... comm"
	@echo "... commproc"
	@echo "... src/comm.o"
	@echo "... src/comm.i"
	@echo "... src/comm.s"
	@echo "... src/commproc.o"
	@echo "... src/commproc.i"
	@echo "... src/commproc.s"
	@echo "... src/lib.o"
	@echo "... src/lib.i"
	@echo "... src/lib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

